vich_uploader:
    db_driver: orm


    mappings:
        articles_image:
            uri_prefix: /img/articles
            upload_destination: '%kernel.project_dir%/public/assets/img/article'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
